# Atelier Seaborn

## Contexte 
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT. 
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression, 
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure. 
Après avoir utilisé NumPy pour manipuler les données numériques, Pandas pour importer, nettoyer 
et analyser le dataset et Matplotlib pour réaliser des visualisations, l'étape suivante consiste à se 
servir de Seaborn pour réaliser une analyse exploratoire plus riche des données.

## Structure du projet

### 1) Structurer le projet comme suit : 
atelier_seaborn_iot/ 
│ 
├── data/ 
│   
└── mesures_capteurs.csv 
│    
├── notebooks/ 
│   
└── atelier_seaborn_iot.ipynb
│ 
└── exports/ 
├── temperature.png 
├── temperature.pdf  
└── ...

### 2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data 
### 3) Créer le notebook atelier_seaborn_iot.ipynb

In [1]:
%pip install ipykernel

Requirement already satisfied: ipykernel in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (7.3.0)
Requirement already satisfied: comm>=0.1.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (9.16.1)
Requirement already satisfied: jupyter-client>=8.9.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (1.7.2)
Requirement already satisfied: packaging>=22 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (26.3)
Requirement already satisfied: psutil>=5.7 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (6.5.8)
Requirement already satisfied: traitlets>=5.4.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: pexpect>4.6 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from jupyter-client>=8.9.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from jupyter-client>=8.9.0->ipykernel) (4.16.0)
Requirement already satisfied: platformdirs>=2.5 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.11.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from pexpect>4.6->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.8.2)
Requirement already satisfied: six>=1.5 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure-eval in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Creation du fichier notebook dans le dossier notebooks
# %mkdir atelier_seaborn_iot.ipynb

mkdir: cannot create directory ‘atelier_seaborn_iot.ipynb’: File exists

### 4) Installer et importer seaborn, matplotlib, pandas, numpy

In [ ]:
# Installation (si besoin, décommenter)
# !pip install pandas numpy matplotlib seaborn

#%pip install numpy pandas matplotlib seaborn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
%matplotlib inline

Requirement already satisfied: numpy in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (2.5.2)
Requirement already satisfied: pandas in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: matplotlib in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (3.11.1)
Requirement already satisfied: seaborn in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/diamata/atelier_seaborn_iot/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### 5) Importer mesures_capteurs.csv dans le dataframe df

**Pour importer le fichier csv dans le dataframe df il faut:**
Charge le CSV dans un DataFrame pandas (tableau exploitable). Le ../ remonte d'un dossier depuis notebooks/ pour aller chercher data/.

In [ ]:
df = pd.read_csv("../data/mesures_capteurs.csv")
#df.head() affiche les 5 premières lignes, pour vérifier que l'import est correct.
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 6) Vérifier le contenu du dataframe df

In [12]:
#df.info() Structure du tableau : colonnes, types, valeurs non-nulles par colonne.
df.info()
print("_________________________________________________________________________________")
#df.isna().sum() Nombre de valeurs manquantes par colonne.
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB
_________________________________________________________________________________

id_mesure       0
date_heure      0
id_capteur      0
batiment        0
temperature     6
humidite        5
pression        5
consommation    5
etat            4
dtype: int64

In [13]:
#df.describe() Statistiques des colonnes numériques : moyenne, min, max, quartiles.
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000